//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Netflix.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASSIFY
    {
        public int CATEGORY_ID { get; set; }
        public int MOVIE_ID { get; set; }
        public int ACTIVE { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual MOVIE MOVIE { get; set; }
    }
}
