//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Netflix.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOVIE()
        {
            this.CREDITS = new HashSet<CREDIT>();
            this.FAVOURITE_MOVIES = new HashSet<FAVOURITE_MOVIES>();
        }
        
        private string _P;
        private string _Tr;
        private string _Mo;

        private string path_movie = @"D:\Netflix02\Netflix\Movie\";
        private string path_poster = @"D:\Netflix02\Netflix\Movie\Poster\";
        public int ID { get; set; }
        public string NAME { get; set; }
        public int INFORMATION { get; set; }
        public string POSTER { get { return path_poster + _P; } set { _P = value; } }
        public string TRAILER_NAME { get { return path_movie + _Tr; } set { _Tr = value; } }
        public string MOVIE_NAME { get { return path_movie + _Mo; } set { _Mo = value; } }
        public int TYPE_ID { get; set; }
        public int CATEGORY_ID { get; set; }
        public int ACTIVE { get; set; }
        public int VIEWS { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CREDIT> CREDITS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAVOURITE_MOVIES> FAVOURITE_MOVIES { get; set; }
        public virtual MOVIE_INFORMATION MOVIE_INFORMATION { get; set; }
        public virtual MOVIE_TYPE MOVIE_TYPE { get; set; }
    }
}
