//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Netflix.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIE_INFORMATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOVIE_INFORMATION()
        {
            this.MOVIEs = new HashSet<MOVIE>();
        }
    
        public int ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> LENGTH { get; set; }
        public Nullable<double> RATE { get; set; }
        public Nullable<int> DISTRIBUTE_YEAR { get; set; }
        public string COUNTRY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIE> MOVIEs { get; set; }
    }
}
