//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Netflix.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOVIE()
        {
            this.CLASSIFies = new HashSet<CLASSIFY>();
            this.CREDITS = new HashSet<CREDIT>();
            this.FAVOURITE_MOVIES = new HashSet<FAVOURITE_MOVIES>();
            this.PURCHASE_INFORMATION = new HashSet<PURCHASE_INFORMATION>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> INFORMATION { get; set; }
        public string POSTER { get; set; }
        public string TRAILER { get; set; }
        public string MOVIE1 { get; set; }
        public int ACTIVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLASSIFY> CLASSIFies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CREDIT> CREDITS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAVOURITE_MOVIES> FAVOURITE_MOVIES { get; set; }
        public virtual MOVIE_INFORMATION MOVIE_INFORMATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASE_INFORMATION> PURCHASE_INFORMATION { get; set; }
    }
}
