//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Netflix.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NETFLIX_DBEntities : DbContext
    {
        public NETFLIX_DBEntities()
            : base("name=NETFLIX_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<ACCOUNT_TYPE> ACCOUNT_TYPE { get; set; }
        public virtual DbSet<CATEGORY> CATEGORies { get; set; }
        public virtual DbSet<FAVOURITE_MOVIES> FAVOURITE_MOVIES { get; set; }
        public virtual DbSet<MOVIE> MOVIEs { get; set; }
        public virtual DbSet<MOVIE_INFORMATION> MOVIE_INFORMATION { get; set; }
        public virtual DbSet<MOVIE_TYPE> MOVIE_TYPE { get; set; }
        public virtual DbSet<PACKAGE> PACKAGEs { get; set; }
        public virtual DbSet<PURCHASE> PURCHASEs { get; set; }
        public virtual DbSet<USER_INFORMATION> USER_INFORMATION { get; set; }
    }
}
