//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Netflix.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURCHASE
    {
        public int ID { get; set; }
        public System.DateTime PURCHASED_DATE { get; set; }
        public System.DateTime OUTOFDATE { get; set; }
        public Nullable<int> PACKAGE_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual PACKAGE PACKAGE { get; set; }
    }
}
